config/routes.rb
Rails.application.routes.draw do
  resources :logentries

  resources :logbooks

  resources :intensities

  resources :sports

  resources :clubs

  root to: 'logentries#index'
  devise_for :users
  resources :users
end

app/models/club.rb
class Club < ActiveRecord::Base
end

app/models/intensity.rb
class Intensity < ActiveRecord::Base
end

app/models/logbook.rb
class Logbook < ActiveRecord::Base
  belongs_to :club
  belongs_to :user
end

app/models/logentry.rb
class Logentry < ActiveRecord::Base
  belongs_to :logbook
  belongs_to :sport
  belongs_to :intensity

  validates_presence_of :start
  validates_presence_of :sport
  validates_presence_of :intensity


  validates :runtime , numericality: { greater_than_or_equal_to: 0, allow_nil: true}
  validates :distance , numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :lactat , numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :avg_heart_rate , numericality: { greater_than_or_equal_to: 0, allow_nil: true }
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 
 respond_to :js, :html
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  def index
    @clubs = Club.all
    respond_with(@clubs)
  end

  def show
    respond_with(@club)
  end

  def new
    @club = Club.new
    respond_with(@club)
  end

  def edit
  end

  def create
    @club = Club.new(club_params)
    flash[:notice] = 'Club was successfully created.' if @club.save
    respond_with(@club)
  end

  def update
    flash[:notice] = 'Club was successfully updated.' if @club.update(club_params)
    respond_with(@club)
  end

  def destroy
    @club.destroy
    respond_with(@club)
  end

  private
    def set_club
      @club = Club.find(params[:id])
    end

    def club_params
      params.require(:club).permit(:name)
    end
end

app/controllers/intensities_controller.rb
class IntensitiesController < ApplicationController
  before_action :set_intensity, only: [:show, :edit, :update, :destroy]

  def index
    @intensities = Intensity.all
    respond_with(@intensities)
  end

  def show
    respond_with(@intensity)
  end

  def new
    @intensity = Intensity.new
    respond_with(@intensity)
  end

  def edit
  end

  def create
    @intensity = Intensity.new(intensity_params)
    @intensity.save
    respond_with(@intensity)
  end

  def update
    @intensity.update(intensity_params)
    respond_with(@intensity)
  end

  def destroy
    @intensity.destroy
    respond_with(@intensity)
  end

  private
    def set_intensity
      @intensity = Intensity.find(params[:id])
    end

    def intensity_params
      params.require(:intensity).permit(:name)
    end
end

app/controllers/logbooks_controller.rb
class LogbooksController < ApplicationController
  before_action :set_logbook, only: [:show, :edit, :update, :destroy]

  def index
    @logbooks = Logbook.all
    respond_with(@logbooks)
  end

  def show
    respond_with(@logbook)
  end

  def new
    @logbook = Logbook.new
    respond_with(@logbook)
  end

  def edit
  end

  def create
    @logbook = Logbook.new(logbook_params)
    @logbook.save
    respond_with(@logbook)
  end

  def update
    @logbook.update(logbook_params)
    respond_with(@logbook)
  end

  def destroy
    @logbook.destroy
    respond_with(@logbook)
  end

  private
    def set_logbook
      @logbook = Logbook.find(params[:id])
    end

    def logbook_params
      params.require(:logbook).permit(:year, :club_id, :user_id)
    end
end

app/controllers/logentries_controller.rb
class LogentriesController < ApplicationController
  before_action :set_logentry, only: [:show, :edit, :update, :destroy]

  def index
    lb = Logbook.where(user: current_user)
    @logentries = Logentry.where(logbook: lb )
    respond_with(@logentries)
  end

  def show
    respond_with(@logentry)
  end

  def new
    lb = Logbook.where(user: current_user).first

	if ( lb == nil )
	  lb = Logbook.new()
	  lb.year = '2014-01-01 00:00:00'
	  lb.club = Club.where(name: 'See-Club Zug').first
	  lb.user = current_user
	  lb.save
	end


	sp = Sport.where(name: 'Rudern').first	
	inten = Intensity.where(name: 'ga1').first

    @logentry = Logentry.new(:logbook_id => lb.id,:sport_id =>sp.id,:intensity_id => inten.id )
    respond_with(@logentry)
  end

  def edit
  end

  def create
    @logentry = Logentry.new(logentry_params)
    @logentry.save
    respond_with(@logentry)
  end

  def update
    @logentry.update(logentry_params)
    respond_with(@logentry)
  end

  def destroy
    @logentry.destroy
    respond_with(@logentry)
  end

  private
    def set_logentry
      @logentry = Logentry.find(params[:id])
    end

    def logentry_params
      params.require(:logentry).permit(:start, :logbook_id, :sport_id, :intensity_id, :runtime, :distance, :avg_heart_rate, :lactat)
    end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  def index
    @sports = Sport.all
    respond_with(@sports)
  end

  def show
    respond_with(@sport)
  end

  def new
    @sport = Sport.new
    respond_with(@sport)
  end

  def edit
  end

  def create
    @sport = Sport.new(sport_params)
    @sport.save
    respond_with(@sport)
  end

  def update
    @sport.update(sport_params)
    respond_with(@sport)
  end

  def destroy
    @sport.destroy
    respond_with(@sport)
  end

  private
    def set_sport
      @sport = Sport.find(params[:id])
    end

    def sport_params
      params.require(:sport).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/intensities_helper.rb
module IntensitiesHelper
end

app/helpers/logbooks_helper.rb
module LogbooksHelper
end

app/helpers/logentries_helper.rb
module LogentriesHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/clubs/_form.html.erb
<%= simple_form_for(@club) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/intensities/_form.html.erb
<%= simple_form_for(@intensity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/intensities/edit.html.erb
<h1>Editing intensity</h1>

<%= render 'form' %>

<%= link_to 'Show', @intensity %> |
<%= link_to 'Back', intensities_path %>

app/views/intensities/index.html.erb
<h1>Listing intensities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @intensities.each do |intensity| %>
      <tr>
        <td><%= intensity.name %></td>
        <td><%= link_to 'Show', intensity %></td>
        <td><%= link_to 'Edit', edit_intensity_path(intensity) %></td>
        <td><%= link_to 'Destroy', intensity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intensity', new_intensity_path %>

app/views/intensities/new.html.erb
<h1>New intensity</h1>

<%= render 'form' %>

<%= link_to 'Back', intensities_path %>

app/views/intensities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @intensity.name %>
</p>

<%= link_to 'Edit', edit_intensity_path(@intensity) %> |
<%= link_to 'Back', intensities_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Activities', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Neuer Eintrag', new_logentry_path %></li>
  <li><%= link_to 'Benutzereinstellungen', edit_user_registration_path %></li>
  <li><%= link_to 'Abmelden', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Anmelden', new_user_session_path %></li>
  <li><%= link_to 'Registrieren', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sweatlog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sweatlog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/logbooks/_form.html.erb
<%= simple_form_for(@logbook) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :year %>
    <%= f.association :club %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/logbooks/edit.html.erb
<h1>Editing logbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @logbook %> |
<%= link_to 'Back', logbooks_path %>

app/views/logbooks/index.html.erb
<h1>Listing logbooks</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Club</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logbooks.each do |logbook| %>
      <tr>
        <td><%= logbook.year %></td>
        <td><%= logbook.club %></td>
        <td><%= logbook.user %></td>
        <td><%= link_to 'Show', logbook %></td>
        <td><%= link_to 'Edit', edit_logbook_path(logbook) %></td>
        <td><%= link_to 'Destroy', logbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logbook', new_logbook_path %>

app/views/logbooks/new.html.erb
<h1>New logbook</h1>

<%= render 'form' %>

<%= link_to 'Back', logbooks_path %>

app/views/logbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @logbook.year %>
</p>

<p>
  <strong>Club:</strong>
  <%= @logbook.club %>
</p>

<p>
  <strong>User:</strong>
  <%= @logbook.user %>
</p>

<%= link_to 'Edit', edit_logbook_path(@logbook) %> |
<%= link_to 'Back', logbooks_path %>

app/views/logentries/_form.html.erb
<%= simple_form_for(@logentry) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start, as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%d.%m.%Y %HH:%MM') } %>  
   
    <%= f.association :sport %>
    <%= f.association :intensity ,:label => 'Intensität'%>
    <%= f.input :runtime, :label => 'Dauer in Minuten' %>
    <%= f.input :distance ,:label => 'Distanz in km' %>
    <%= f.input :avg_heart_rate ,:label => 'durchschnittl. Puls' %>
    <%= f.input :lactat ,:label => 'Laktat in mmol'%>

    <%= f.association :logbook, input_html: { hidden: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/logentries/edit.html.erb
<h5>Editing logentry</h5>

<%= render 'form' %>

<%= link_to 'Show', @logentry %> |
<%= link_to 'Back', logentries_path %>

app/views/logentries/index.html.erb
<% if user_signed_in? %>



<h5>Activities</h5>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>Sportart</th>
      <th>Intensitaet</th>
      <th>Dauer</th>

      <th>Distanz</th>
      <th>Puls Durchschn</th>
      <th>Lactat in mmol</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @logentries.each do |logentry| %>
      <tr>
        <td><%= logentry.start %></td>
        <td><%= logentry.sport.name %></td>
        <td><%= logentry.intensity.name %></td>
	<td><%= logentry.runtime %></td>
        <td><%= logentry.distance %></td>
        <td><%= logentry.avg_heart_rate %></td>
        <td><%= logentry.lactat %></td>
        <!-- <td><%= link_to 'Show', logentry %></td> -->
        <td><%= link_to 'Bearbeiten', edit_logentry_path(logentry) %></td>
        <td><%= link_to 'Entfernen', logentry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logentry', new_logentry_path %>

<% else %>

<h5>Sweatlog !</h5>

<% end %>

app/views/logentries/new.html.erb
<h5>New logentry</h5>

<%= render 'form' %>

<%= link_to 'Back', logentries_path %>

app/views/logentries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @logentry.start %>
</p>

<p>
  <strong>Sportart:</strong>
  <%= @logentry.sport.name %>
</p>

<p>
  <strong>Intensität:</strong>
  <%= @logentry.intensity.name %>
</p>

<p>
  <strong>Dauer </strong>
  <%= @logentry.runtime %>
  <strong> Min. </strong>		
</p>

<p>
  <strong>Distanz :</strong>
  <%= @logentry.distance %>
 <strong>Km</strong>


</p>

<p>
  <strong>durchschnittl. Puls:</strong>
  <%= @logentry.avg_heart_rate %>
</p>

<p>
  <strong>Laktat in mmol :</strong>
  <%= @logentry.lactat %>
</p>

<%= link_to 'Bearbeiten', edit_logentry_path(@logentry) %> |
<%= link_to 'Neuer Logeintrag', new_logentry_path %>
<%= link_to 'Uebersicht', logentries_path %>

app/views/sports/_form.html.erb
<%= simple_form_for(@sport) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.name %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>
        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sport.name %>
</p>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h5>Welcome to Sweatlog</h5>
<p>Please register to log you activity !</p>